sudo: required
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker build -t "$DOCKER_USERNAME"/twitter-integration .
script:
  - echo "npm test temporarily disabled"
  - docker images "$DOCKER_USERNAME"/twitter-integration
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_USERNAME"/twitter-integration;
    fi
notifications:
  email: false

