sudo: required
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - docker
before_install:
  - docker build -t piyush240591/twitter-integration .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
script: echo "npm test temporarily disabled"
notifications:
  email: false

