sudo: required
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
env:
  - COMMIT=${TRAVIS_COMMIT::8}
services:
  - docker
before_install:
  - docker build -t "$DOCKER_USERNAME"/twitter-integration:$COMMIT .
script:
  - echo "npm test temporarily disabled"
  - docker images "$DOCKER_USERNAME"/twitter-integration
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "$DOCKER_USERNAME"/twitter-integration:$COMMIT "$DOCKER_USERNAME"/twitter-integration:$REPO:travis-$TRAVIS_BUILD_NUMBER;
    docker push "$DOCKER_USERNAME"/twitter-integration:travis-$TRAVIS_BUILD_NUMBER;
    fi
notifications:
  email: false

